import type { Metadata } from "next";

import Figure from "@/components/Figure";
import ProjectPage from "@/components/ProjectPage";
import Video from "@/components/Video";
import { getProject } from "@/lib/projects";

const project = getProject("vrl");

export const metadata: Metadata = {
  title: project.title,
  description: project.summary,
};

export default function Vrl() {
  return (
    <ProjectPage project={project}>
      <h2>Problem context</h2>
      <p>
        Video prediction is considered to be a more challenging task than
        language prediction. Given the previous frames of a video, the challenge
        lies in how a program can predict what will happen next. The difficulty
        further increases when combining prediction with semantic segmentation,
        as the system needs to both predict the future and segment semantic
        objects from the future scene. In this project, we were provided with 22
        consecutive frames of images, and the task was to predict the semantic
        masks for all 22 frames using only the first 11 frames. During the
        course, we attempted to use two separate models:{" "}
        <a
          href="https://github.com/milesial/Pytorch-UNet.git"
          target="_blank"
          rel="noreferrer"
        >
          UNet
        </a>{" "}
        for semantic segmentation and{" "}
        <a
          href="https://github.com/A4Bio/SimVP.git"
          target="_blank"
          rel="noreferrer"
        >
          SimVP
        </a>{" "}
        for video prediction. We also explored the potential of using a Vector
        Quantized Variational AutoEncoder (
        <a
          href="https://arxiv.org/abs/1711.00937"
          target="_blank"
          rel="noreferrer"
        >
          VQ-VAE
        </a>
        ) for video representation pre-training and semantic prediction
        fine-tuning.
      </p>

      <Video src="/vrlproblem.mp4" />

      <h2>Implementation</h2>
      <p>
        The training scheme of the initial attempt is shown below. First, we
        used a UNet for semantic segmentation training with cross-entropy loss.
        Second, SimVP — a structure consisting of a spatial encoder, temporal
        prediction, and spatial decoder — was employed to predict the
        pixel-level future. Finally, we combined the two models mentioned above
        and fine-tuned the spatial decoder with semantic segmentation while
        freezing the first two parts.
      </p>

      <Figure
        src="/vrlframe.jpg"
        alt="Three-stage training scheme for video semantic prediction"
        width={2876}
        height={1596}
        caption="Figure 1: The three-stage training scheme for video semantic prediction learning"
      />

      <h2>Results</h2>
      <p>
        Visualized results are shown below. The predicted images became blurred
        for the more distant future, leading to less accurate semantic mask
        results. It turned out that dividing the task into two steps — first
        predicting the pixels and then segmenting the predicted pixels — might
        not be a good idea. Instead, it makes more sense to convert the pixel
        images to a latent representation and then predict the latent
        representation, which led to the second idea of VQ-VAE pre-training.
      </p>

      <Video src="/vrlresult.mp4" />

      <p>
        The first step of the VQ-VAE method is to generate the image using an
        autoencoder architecture. The encoder converts the images into a latent
        embedding, the quantizer maps the output embedding to the nearest
        embedding in its trainable codebook, and finally the nearest embedding
        is forwarded into the decoder to reconstruct the original images. The
        mean squared error between the reconstructed and original images is used
        to optimize the VQ-VAE model. Sample generated images are shown below.
        Once we have obtained a good embedding encoder, we can use it for video
        prediction and semantic segmentation in the next step.
      </p>

      <Figure
        src="/vqvae.jpg"
        alt="Images generated by the VQ-VAE encoder alongside the originals"
        width={2876}
        height={1572}
        caption="Figure 2: Images generated by the encoder of VQ-VAE (right), and the original image (left)"
      />
    </ProjectPage>
  );
}
